### ISSUE TITLE
Autocomplete does not match data correctly.

### ISSUE THREAD

**Issue by JimBobSquarePants** [uComponents/nuPickers#104]
Using the Autocomplete picker in the backoffice the name "Hampton" was not matched when querying a set of data. "Wolverhampton" was matched instead. Using the jQuery UI autocomplete in the front end against the same data source the match was correct.

**Comment by Hendy** [comment]
@JimBobSquarePants I had a look on the internal project this refers to, and the reason is that the datatype was configured to return a single option - "Wolverhampton" just happened to be the first match.. I've changed the "Limit To" from 1 to 0 so that the number of matched results isn't limited.

**Comment by JimBobSquarePants** [comment]
A brilliant. Thanks!
