### ISSUE TITLE
Prevents Umbraco core update

### ISSUE THREAD

**Issue by enkelmedia** [uComponents/nuPickers#107]
I tried to upgrade the Umbraco core for one of my projects today from version 7.2.0 to 7.2.8. During the first startup after the install when the install-screen should show the browser console complained about that lazyload.js could not load a bunch of resource files associated with NuPickers.

After moving the nupicker-dll out of the bin-folder the upgrade wizard started as expected.

**Comment by Jeavon** [comment]
Fixed in v1.5.2
