### ISSUE TITLE
Xpath trailing /*

### ISSUE THREAD

**Issue by purna** [uComponents/nuPickers#108]
Any reason that this would work

$ancestorOrSelf/ancestor-or-self::*[@level=1]/cwsClassifiedAds/cwsContainerLabel[@nodeName='Categories']/cwsLabel

but not this

$ancestorOrSelf/ancestor-or-self::_[@level=1]/cwsClassifiedAds/cwsContainerLabel[@nodeName='Categories']/_*

**Comment by greystate** [comment]
The top one returns a single element/value - the bottom one returns a set (all properties and child documents of the `cwsContainerLabel` named "Categories").
