### ISSUE TITLE
Missing Images

### ISSUE THREAD

**Issue by JimBobSquarePants** [uComponents/nuPickers#111]
I think this issue has been introduced as a result of the updates related to embedded resources. When using the list picker I get a 404 for the images. I'll try to get some time to investigate.

I'm running Nupickers 1.5.1 with Umbraco 7.2.8.
    
    GET http://mcn.com.au.localhost/App_Plugins/nuPickers/Shared/ListPicker/ButtonAdd.png 404 (Not Found)

**Comment by jbreuer** [comment]
I'm also running into this issue. Just upgraded from the Umbraco 7.3 RC to the final and now the images are missing.

**Comment by zpbd** [comment]
Yep, same. Just upgraded from 7.2.8 to 7.3.0, and don't have any files in App_Plugins/nuPickers.

**Comment by Hendy** [comment]
Hi @zpbd just to note, there shouldn't be any files in the App_Plugins/nuPickers folder as they are all embedded within the dll.

**Comment by Jeavon** [comment]
@JimBobSquarePants interestingly I have tracked this down to ImageProcessor v2.3/ImageProcessor.Web v4.4. If I force a downgrade to IP v2.2.8 and Web v4.3.6 it works as it has always done. Any clues as to what might have changed in IP/IP.Web to be stopping the MVC route picking up these requests?

**Comment by JimBobSquarePants** [comment]
@Jeavon Ah that makes perfect sense!

With the new version of ImageProcessor.Web I made the decision to intercept all image requests if RAMMFAR is on to allow optimisation so I can post process them. I kept seeing instances in website where images were being uploaded to the CMS without appropriate optimisation. (I'm all about raw, badass, speed)

In your case the file doesn't actually exists and my httpmodule is intercepting the request before your route.

Now I'm kinda loath to revert that change as it also meant I don't accidentally enlarge some images when pulling them remotely. (Feel free to argue your case though :smile:)

There are a few options here:
1. Add `?ipignore=true` to each image request
2. Write an `IImageService` to retrieve the images much like you are doing work to cater for Client Dependency
3. Replace the images with the built in font icon used in Umbraco #112 

Personally I think 3 would be the best approach since that would then make it look and feel more native to Umbraco and better for content editors.

What do you think?

**Comment by Jeavon** [comment]
@JimBobSquarePants I think we will replace the images with icons but to get a working v7.3 version out there I'll give ipignore=true for now.

**Comment by JimBobSquarePants** [comment]
@Jeavon Any issues give me shout :smile:

**Comment by Jeavon** [comment]
Would love it if anyone has time to try out build 133 https://www.myget.org/gallery/nupickers (there are some other Umbraco v7.3 fixes in there as well)

**Comment by zpbd** [comment]
Hi @Jeavon it seems to be working fine for me now with that build :)

**Comment by Jeavon** [comment]
@zpbd great to hear

**Comment by Jeavon** [comment]
Fixed in v1.5.2

**Comment by JimBobSquarePants** [comment]
Whoop!

**Comment by Jeavon** [comment]
Have discovered that this stops the images working in installs with IP.Web less than v4.4 as of course the querystring is triggering IP to intercept but the file doesn't exist

**Comment by JimBobSquarePants** [comment]
Isn't ImageProcessor.Web v4.4 a dependency for Umbraco v7.3? I thought Nupickers v1.5.2 was released for that version up?

So many version numbers!

**Comment by Jeavon** [comment]
Yes it is. nuPickers v1.5.2 works with Umbraco v7.2.3+ I'm thinking we may just need to only support v7.3.0+....

**Comment by Jeavon** [comment]
Or better we change to using the icon per #112

**Comment by JimBobSquarePants** [comment]
What a wonderful idea! Whoever suggested that must be one smart cookie :grin:
