### ISSUE TITLE
Use Icon font for images

### ISSUE THREAD

**Issue by JimBobSquarePants** [uComponents/nuPickers#112]
I'm wondering whether rather than using the embedded images the solution could use the icon font embedded in umbraco? That way we could maintain a more consistent style with the rest of the CMS.

**Comment by Hendy** [comment]
Hi @JimBobSquarePants do you know of a list of icons available ? I can see the CSS references a font called icomoon, so guessed [these](https://icomoon.io/#preview-free) but some seem to be there, some not.

**Comment by Jeavon** [comment]
@hendy I'm pretty sure it's hlvticons http://hlvticons.ch/

**Comment by Hendy** [comment]
Thanks @Jeavon. Have replaced the images with icons, but think the CSS still needs a little tweaking - should the icon turn black and underlined on hover (as it's an anchor tag) ?

**Comment by JimBobSquarePants** [comment]
I would say there should be interactive states yes.  I did notice the other day though that Umbraco natively has a constant underline with no interactive state for links.
