### ISSUE TITLE
nuPicker PrefetchList Save Format: JSON / CSV - why? Single source of truth?

### ISSUE THREAD

**Issue by azsam** [uComponents/nuPickers#114]
Hello,

as far as I can see nuPickers save relations in the table "umbracoRelation", which is absolutely fine. One could easily query relations between objects. 
What we don't get is - why the same data is being saved, once again, in another table - namely cmsPropertyData. Isn't that an antipattern having the same information in two tables? It could easily lead to a synchronization problem if the database crashes during update.

Thanks!

**Comment by Hendy** [comment]
Hi @azsam you can configure data to be stored in either place (or both). Normally a property editor will strore data in cmsPropertyData (which is also loaded into the cache), but if you select "Relations Only" then data will only be saved in the umbracoRelation table.
