### ISSUE TITLE
JsonDataSource.cs source throws NullReferenceException at line 47

### ISSUE THREAD

**Issue by csharpforevermore** [uComponents/nuPickers#115]
I find that with an install of Umbraco 7.3.1 and nuPickers 1.5.2, if I try and create a Json Data Source of any kind, I get no results. When checking the browser I see that the following request is failing:

>POST http://site.local/umbraco/backoffice/nuPickers/JsonDataSourceApi/GetEditorDataItems currentId=1545&parentId=1496&propertyAlias=memberGroups

It seems like the nuPickers.Shared.JsonDataSource.JsonDataSource is failing at  line 47. It seems the EditorDataItem anonymous constructor is failing because the JObject.SelectToken() method returns null so the ToString() method fails.

**Comment by csharpforevermore** [comment]
The JSON I tested it with was the following 

> {"Name":"Event 11/03/2015 04:4855","Sites":[{"Id":1096,"Parent":"www.site1.com","IsSelected":false},{"Id":1097,"Parent":"www.site2.com","IsSelected":false},{"Id":1098,"Parent":"www.members.com","IsSelected":false}],"MemberGroups":[{"Name":"Type Y Member","IsSelected":false,"Key":"8fb78808-a50d-4600-8066-03dd4526c380"},{"Name":"Type X Member","IsSelected":false,"Key":"8c87c55a-7caf-4f74-8476-4eaef9c15556"}]}

JSONKeypath = $..*
Key JSONPath = Id 
Label JSONPath = Parent

**Comment by Hendy** [comment]
Hi @csharpforevermore, try changing your JSONPath to: 

$.Sites[*]

This will return a subset of data suitable for your Key and Label JSONPaths.

HTH,
Hendy

(this is a useful tester: https://jsonpath.curiousconcept.com/)

**Comment by Hendy** [comment]
Marked as a bug, as null exception shouldn't be thrown (code currently expects all JSONPath expressions to return data)

**Comment by csharpforevermore** [comment]
That's great @Hendy - thanks my good man! I love the work you've done. It's a pity there's no XPath / JSONPath query testers for 7.3.0 / 7.3.1 yet to see what the results of JSONPath is without having to keep switching between the content section's doctype and the developer section's data type.

**Comment by Hendy** [comment]
see branch: https://github.com/uComponents/nuPickers/tree/hotfix/issue-115
