### ISSUE TITLE
Form Picker

### ISSUE THREAD

**Issue by purna** [uComponents/nuPickers#118]
Is it possible to have a typeahead form picker?

**Comment by Hendy** [comment]
Hi @purna how do you mean ?

**Comment by purna** [comment]
Hi @Hendy 

Thanks for the response

I have one site that has over 100 competition forms, if possible I would like to be able to use a  nuPicker selector to choose a Contour / Form rather than the current 'FormPicker' datatype which list all the forms on the page. 

Hope this makes sense.

**Comment by Hendy** [comment]
Hi @purna, I'm not familiar with how contour forms are stored - are they in the database ? if so, the Sql PrefetchList Picker should be able to do the job - otherwise a DotNet PrefectchList Picker can be used with any custom logic to get at the available contour forms.

**Comment by purna** [comment]
Thanks Henry

I'm getting an error 'Object must implement IConvertible' when using the Sql
PrefetchList Picker

SELECT
Id AS 'Key',
Name AS 'Label'
FROM UFForms
WHERE Archived = 0
ORDER BY Name

In this case the Id is a  'GUID' and not an int.

Shame that would have been a perfect solution. Lol

**Comment by Hendy** [comment]
HI @purna, I think both the Key and Label fields are strings, so should be possible to cast the GUID to a string in your SQL, perhaps something like the following will work ?

    SELECT
    CAST(Id AS NVARCHAR(36)) AS 'Key',
    Name AS 'Label'
    FROM UForms
    WHERE Archived = 0
    ORDER BY Name

**Comment by purna** [comment]
Fantastic - Thank you
