### ISSUE TITLE
Prevalues dont work with DotNetPickers any more

### ISSUE THREAD

**Issue by iahdevelop** [uComponents/nuPickers#121]
I have DotNetPickers with prevalue fields, and when i upgraded to 1.5.2 they stopped working. all i get in the IDotNetSource is null.

**Comment by Hendy** [comment]
Hi Ibrahim, would you be able to provide any details that could help identify the cause of this issue ?
Is it limited to DotNetPickers ? What version did you upgrade from ?
Thanks, Hendy

**Comment by iahdevelop** [comment]
Hello Hendi

I think i figured out the problem, I'm using Grid Doctype package to inject content into the grid. and i'm using the SQL picker and the DotNet Picker. The SQL picker is working fine, but DotNet Picker is not working. Actually it didnt make any request to the server to bring data.

Thanks, Ibrahim

**Comment by Hendy** [comment]
Hi Ibrahim, Is it all working for you now ? if not, just wondering if the DotNet picker was a DropDown & and you're using Chrome ?

**Comment by iahdevelop** [comment]
Hi Hendy

Yes, I'm using DotNet Dropdown picker and Chrome. But i figured out the problem. When i used Doctype Grid Editor to inject data into the grid, it didn't pass the contextId and passed the parentId -20. so i did some modification to Doctype controller to pass the contextId and it worked fine.

Thanks.
