### ISSUE TITLE
TypeAheadListPicker's are allowing CSV format on create

### ISSUE THREAD

**Issue by dillorscroft** [uComponents/nuPickers#125]
When you first create a TypeAheadListPicker it incorrectly allows you to use CSV as the Save format.  

The data type doesnt render properly when used in a document type after first save.

**Comment by Hendy** [comment]
Hi @dillorscroft, don't suppose you can recall what versions of Umbraco / nuPickers this was with ? (I think an old release may have had this issue)

Do you think the second issue a likely consequence of the first ?

Thanks

**Comment by dillorscroft** [comment]
@Hendy 

Yes they are both directly related.  This was on a live project from only two weeks ago.  V7.3.4 Umbraco and the nuget package from that date.  Pretty certain I can still replicate but will check when home.

**Comment by Hendy** [comment]
Hi @dillorscroft can this issue be closed ? (unable to replicate this)

**Comment by dillorscroft** [comment]
Hi... yes I can no longer replicate.  Maybe fixed after an update.

**Comment by dillorscroft** [comment]
^ Actually... it's not on create.  Once created and saved you can then revert to Save Format to CSV.

**Comment by Hendy** [comment]
Thanks @dillorscroft, do you see any console errors, and what version of nuPickers / which Typeahead Picker is this ?

**Comment by Hendy** [comment]
code with the bug has been removed, as typeahead pickers now support csv
