### ISSUE TITLE
Performance issue when using lots of Picker values on a node

### ISSUE THREAD

**Issue by netaddicts** [uComponents/nuPickers#127]
Seems you're hitting the database for each Picker value. See https://github.com/uComponents/nuPickers/blob/1848f2f65df368ab67b856e8ca8f452bc45a2db9/source/nuPickers/Picker.cs#L217

**Comment by sniffdk** [comment]
Yes, in it's current state .AsPublishedContent should be avoided :smiley:

**Comment by Hendy** [comment]
Arh, the uQuery.GetUmbracoObjectType call... yes I think that could be replaced with:

            IPublishedContent publishedContent = null;

            publishedContent = umbracoHelper.TypedContent(id);

            if (publishedContent == null)
            {
                // fallback to attempting to get media
                publishedContent = umbracoHelper.TypedMedia(id);
            }

            if (publishedContent == null)
            {
                // fallback to attempting to get member
                try
                {
                    publishedContent = umbracoHelper.TypedMember(id);
                }
                catch
                {
                    // HACK: suppress Umbraco error
                }
            }

            return publishedContent;

**Comment by netaddicts** [comment]
Ok, did something wrong trying to provide a fix, was cloning repo but should've forked first...

Here's my fix which does the same

````csharp
Attempt<int> attemptNodeId = pickedKey.TryConvertTo<int>();
if (attemptNodeId.Success)
{                   publishedContent.Add(umbracoHelper.TypedContent(attemptNodeId.Result) ?? umbracoHelper.TypedMedia(attemptNodeId.Result) ?? umbracoHelper.TypedMember(attemptNodeId.Result));
}
````

**Comment by netaddicts** [comment]
@Hendy  Do you want me to pull request this one?

**Comment by sniffdk** [comment]
Actually, it seems that uQuery.GetUmbracoObjectType is used in the constructor as well .. -> https://github.com/uComponents/nuPickers/blob/1848f2f65df368ab67b856e8ca8f452bc45a2db9/source/nuPickers/Picker.cs#L42

**Comment by Hendy** [comment]
arh null coalescing, much nicer :+1: but I think the umbracoHelper.TypedMember will throw an error if the id can't be found - perhaps this has now changed in Umbraco ?

**Comment by leekelleher** [comment]
Sorry to jump in on this one, (was just chatting with @netaddicts) ... we do something similar in Ditto, but set a flag for when used in a loop.

https://github.com/leekelleher/umbraco-ditto/blob/develop/src/Our.Umbraco.Ditto/ComponentModel/Processors/UmbracoPickerAttribute.cs#L105-L107

**Comment by Hendy** [comment]
@netaddicts that'd be great ! just wondering where to put a replacement helper method for the uQuery.GetUmbracoObjectType(int) ?

**Comment by sniffdk** [comment]
@leekelleher yeah, it's not pretty :laughing:

**Comment by leekelleher** [comment]
@sniffdk _Don't let James South hear you say that?_ LOL ;-)
It's the lesser of the evils, preventing the db hit from the front-end.

**Comment by sniffdk** [comment]
@leekelleher haha :smile: but yeah, it avoids db hits so it's fine.
