### ISSUE TITLE
Layout Direction "Horizontal" has no effect for CheckBox Picker

### ISSUE THREAD

**Issue by greystate** [uComponents/nuPickers#131]
Setting the layout direction to "horizontal" does not change the layout of checkboxes in a CheckBox Picker - based on the CSS in [LayoutDirection.css](https://github.com/uComponents/nuPickers/blob/63c151763f6f9b5c8f467afd2f12504498bf8d8b/source/nuPickers/Shared/LayoutDirection/LayoutDirection.css) it's probably because the `<label>` inside the `<li>` still has `display: block` applied to it.

**Comment by Hendy** [comment]
Hi @greystate I've not been able to reproduce this yet (tried with Chrome & IE11 on Windows 8.1/ Umbraco 7.2.4). The label element is using an Umbraco CSS style and being set to display:inline-block. I'll try again with the latest version of Umbraco...

**Comment by greystate** [comment]
Ah - that could be related to the version, yes. I Anne-Mette currently using v7.4.0-RC1 (reported from the beta2, if I remember correctly)
