### ISSUE TITLE
GetEditorDataItems hangs randomly

### ISSUE THREAD

**Issue by greystate** [uComponents/nuPickers#133]
I'm having issues with an _XmlCheckBoxPicker_ I've set up to show a list of tags.

The checkboxes are randomly not displaying (the **Toggle All** checkbox displays and the counter as well, showing **(0/0)** though) but no boxes are shown.
Checking the inspector, I can see the call to `GetEditorDataItems` is still executing. After about 2 minutes, it completes and the checkboxes are shown.

At the moment there are ~26 checkboxes, but they display fine at other times without delay.

Currently the site is in development, so still running in debug mode. Don't know if that could be a factor...

**Comment by greystate** [comment]
@Hendy Have you seen this problem on any sites using nuPickers?

**Comment by Hendy** [comment]
Hi @greystate, it's not an issue I've encountered - is there a way to consistently reproduce this issue ?

**Comment by greystate** [comment]
Just did some tweaking - looks like it's related to using **Custom Labels** - which of course makes sense (running a macro for every item)... :(

**Comment by Hendy** [comment]
oh, any idea if it's possible to speed this up ? perhaps we can introduce a caching option somehow ?

**Comment by greystate** [comment]
Just had a think...
I'm storing all my nuPickers as XML, so actually (related to #89), the rendered custom label is already there; couldn't we just safely use that (essentially) cached version instead of hitting the macro again?

(Unless, of course, the Custom Labels macro is generating random stuff - but again, maybe there could be a "Custom Label only updates when picked node is saved/published" config property to let me specify that I know what I'm doing :-)

**Comment by greystate** [comment]
Another thought: Does the normal macro caching settings make sense for Custom Labels? I'm a little unsure whether **Cache by page** and **Cache personalized** makes sense in a Custom Labels scenario...

**Comment by greystate** [comment]
**Update:** I'm pretty sure this issue was related to a [bug introduced Umbraco 7.4.0](http://issues.umbraco.org/issue/U4-8325) where XSLT macros were flooding the logfiles.
