### ISSUE TITLE
Stale Relations

### ISSUE THREAD

**Issue by thantos** [uComponents/nuPickers#134]
Umbraco 7.4.1
nuPickers 1.5.3
When creating content with a Lucene PreFetch picker with Relations on (media to content) the relations are being saved with a comment that has "-1" for the propertyTypeId and DataTypeDefId.
![image](https://cloud.githubusercontent.com/assets/289213/13835485/7b6a658e-ebc6-11e5-9338-5f4a9f3a4f3d.png)
This causes 
1. stale relations if the mapping is removed 
2. duplicate relations if the mapping is re-added

![image](https://cloud.githubusercontent.com/assets/289213/13835528/ba8bad5e-ebc6-11e5-8b21-ab2235ab2512.png)

Everything works as expected if you save before picking the values.

Thanks for this awesome system!

**Comment by enz1n0** [comment]
Hi thantos,
have you finded a solution? Now I'm filtering comments that don't contain PropertyTypeId="-1"....   :(

**Comment by Hendy** [comment]
Hi @thantos , @enz1n0 would you be able to describe some steps to recreate this issue ? (the -1 values would be used if the picker can't find it's current context, should we just prevent any relations data being stored if the value -1 ?)

**Comment by Hendy** [comment]
Hi, just to add I've asked a question on the [Our Umbraco](https://our.umbraco.org/forum/developing-packages/85047-context-property-value-converters) forum related to this.

**Comment by enz1n0** [comment]
Hi, I have a relation: brandToAssociate (Bidirectional, document to document) and the documentType brand has a property with datatype nuPickers.DotNetCheckBoxPicker (save format is CSV)
the class is:
```
public class NuPickersAssociatesDataSource : IDotNetDataSource
    {
        IEnumerable<KeyValuePair<string, string>> IDotNetDataSource.GetEditorDataItems(int contextId)
        {
            var associateService = DependencyResolver.Current.GetService<AssociateService>();
            var dictionary = associateService.GetAssociatesDictionary();
            return dictionary;
        }
    }
```
If I create a new brand node the relation row in umbracoRelation is 
`<RelationMapping PropertyAlias="brand_associate" PropertyTypeId="-1" DataTypeDefinitionId="-1" />`
if I save again it becomes 
`<RelationMapping PropertyAlias="brand_associate" PropertyTypeId="100" DataTypeDefinitionId="3610" />`
There are some rules on ContentService_OnSaving, but they don't interact with brand documentType

**Comment by Hendy** [comment]
Hi @enz1n0 I've just pushed a change to the Picker constructor which *might* fix this issue (branch 'picker-constructor-refactor). If you'd be willing to test this I can send you a dll if that's any help ?

**Comment by Hendy** [comment]
Hi @enz1n0 I've just pushed a change which *might* fix this issue. The -1 values were set by the PropertyValueConverter when it was unable to find the current published item.

However I will continue to investigate....
