### ISSUE TITLE
Randomly 500 error on getting data

### ISSUE THREAD

**Issue by stefanoberetta** [uComponents/nuPickers#136]
Hi!

Umbraco 7.4.2 and 7.4.3
nuPickers 1.5.3

I'm using from 1 to 3 pickers (json and sql) per page and randomly a picker or all the pickers don't load the data.
The details of the 500 error in 7.4.2 were hidden by a bug (U4-8239).
I've upgraded Umbraco some minutes ago and now I can see the detailed error clearly but I don't know if it is a bug or if something went wrong during the update/installation.
The error is the same for every picker type, always on "GetEditorDataItems" method.

Thank you for your help.

[error.txt](https://github.com/uComponents/nuPickers/files/220547/error.txt)

**Comment by Hendy** [comment]
Hi @stefanoberetta, looked at the file, but unfortunately can't offer any suggestions as to what might be causing this. Closing, but can re-open if it's still an issue.
