### ISSUE TITLE
DotNetPrefetchListPicker: Sorting not persisting and selected items are being removed on save.

### ISSUE THREAD

**Issue by BrockBoyd** [uComponents/nuPickers#137]
Working with nuPickers.DotNetPrefetchListPicker on Umbraco 7.2.8 and NuPickers Ver: 1.5.3

Sorting is not persisting after save/publish.

Selected items are being removed on save/publish.

Reverted back to NuPickers Ver: 1.4.1 for a workaround.

**Comment by Hendy** [comment]
Hi @BrockBoyd do you know if this was using the Relations Only save format ? (if not, we can reopen this issue)

Closing as unable to reproduce this issue, but possibly related to #105 and #161 (if using Relations Only)

**Comment by crashdavis23** [comment]
It was with relations only.

**Comment by Hendy** [comment]
Thanks @crashdavis23
