### ISSUE TITLE
Too much indentation in config

### ISSUE THREAD

**Issue by bjarnef** [uComponents/nuPickers#141]
It seems there is too much indentation in config, because css from nuPickers overwrite core styling.

![image](https://cloud.githubusercontent.com/assets/2919859/16561772/40b4ddee-41fb-11e6-866d-59164ac33ad4.png)

**Comment by bjarnef** [comment]
You can remove the margin and padding added to nuPickers config div.

Instead add `class="control-label` to `<label>` and `class="controls" to the sibling `<div>`

The Umbraco handle the styling and it is consistent with core styling.

![image](https://cloud.githubusercontent.com/assets/2919859/16575873/d030a594-428b-11e6-9d74-8df012270172.png)

**Comment by Hendy** [comment]
Hi @bjarnef, Thanks - just tried this in Umbraco 7.2.4, and it does the opposite ! although guess it makes sense to support the latest Umbraco version ?
![capture](https://cloud.githubusercontent.com/assets/77045/16901100/3a747eea-4c31-11e6-9e29-e98658949fbe.PNG)

**Comment by Jeavon** [comment]
I wonder which version it changes...?

**Comment by Hendy** [comment]
It's going to be a question for all packages - what markup to use to match the Umbraco UI ? sounds like a good use-case for an Umbraco supplied Angular directive, maybe there is one ?

**Comment by bjarnef** [comment]
Hi @Hendy and @Jeavon 

I have tested it in Umbraco 7.2.8 and with the latest release of nuPickers (v.1.5.3) it looks like this:
![image](https://cloud.githubusercontent.com/assets/2919859/16918506/ecf2f7f2-4d05-11e6-86b3-7b69cd8d454c.png)

and with my changes:
![image](https://cloud.githubusercontent.com/assets/2919859/16918528/0a30a486-4d06-11e6-9632-a65b174d6d2d.png)

**Comment by Jeavon** [comment]
So it changed between v7.2.4 and v7.2.8?

**Comment by bjarnef** [comment]
well, in v7.2.7 it is the same as in v7.2.8

**Comment by bjarnef** [comment]
Comparing v7.2.4 and v7.2.7 it seems css has changed for `controls-row` to no longer include `!important` and therefore not overwrite indent of `.form-horizontal .controls`

**v7.2.4**
![image](https://cloud.githubusercontent.com/assets/2919859/16926162/e172efb4-4d27-11e6-8004-bb769c50776e.png)

**v7.2.7**
![image](https://cloud.githubusercontent.com/assets/2919859/16926255/33531e30-4d28-11e6-85ba-87919fd01f0f.png)

**Comment by Jeavon** [comment]
I would be happy shifting our minimum supported version up to v7.2.7 from v7.2.3 @hendy?

**Comment by bjarnef** [comment]
Anyway I think it would be good to add `controls-row` for consistency and if Umbraco change styling for controls-row it affect both the property editor dropdown + alias label + any custom property rows.

**Comment by bjarnef** [comment]
Fixed in https://github.com/uComponents/nuPickers/pull/143/commits/05e19ba20464a435c3b6fa802001f53f83fad7a1

A minor difference between older versions and newer versions of Umbraco (tested from 7.2.7+) where classes `radio` and `checkbox` on labels wrapping checkboxed or radiobuttons is styled different from newer versions.

**Comment by bjarnef** [comment]
@Hendy @Jeavon did you test with the latest commit?

**Comment by Hendy** [comment]
Thanks for the fix @bjarnef 👍 
@Jeavon do you think we need to bump the min version for a cosmetic issue (I've already merged it into master) so perhaps next release is v.1.6.0 ?
