### ISSUE TITLE
Cache Prevalues for the Picker obj

### ISSUE THREAD

**Issue by Hendy** [uComponents/nuPickers#146]
https://our.umbraco.org/projects/backoffice-extensions/nupickers/questionssuggestions/78916-db-calls-during-render#comment-252197

**Comment by drpeck** [comment]
Caching on application start is certainly a sensible approach, but could you not just look at the property value and determine the type based on the content (i.e. 1024,1099 is pretty likely to be CSV and <node>1024</node> is going to be XML). It would also mean that if the format was changed in the datatype then old values wouldn't break. The bug BUT is what about 'relations only', but could you store 'relationsOnly' as the value then? Breaking change I guess...

**Comment by Hendy** [comment]
All prevalues are now cached as a var in the Picker obj after the first query - but we could use memory cache instead ? (and invalidate on save of data-type)

**Comment by drpeck** [comment]
Will that var persist across requests? If so then that sounds like it would resolve things. If not then I can create a PR using memory cache (once you've committed this change) if it would be of interest.

**Comment by Hendy** [comment]
Hi @drpeck, this var caching is already in the wild, but would be good to swap to using a memory cache (so, as you've highlighted, it's not inflated on first hit in each Picker obj), would be great to have a PR for that if you're willing :)

Perhaps the cache invalidation event would be in a class in the root called PickerCacheInvalidationEvents.cs ?

(have also been thinking of using memory cache for Picked items (key + label), so that the CSV & Relations only save formats, don't have to make another query to re-inflate)

**Comment by drpeck** [comment]
@Hendy It's on my TODO list. If by any chance I've not sorted in a timely manner than prompt me.

**Comment by Hendy** [comment]
sorry @drpeck, I couldn't help myself :) (should be fixed now tho, and the cache can be put to use on relations & CSV labels - via a config option maybe ?)

**Comment by drpeck** [comment]
:-) No worries at all. It saves me the effort. Any reason for not using `ApplicationContext.ApplicationCache.RuntimeCache`?

I look forward to this appearing in a release.

**Comment by Hendy** [comment]
Hi @drpeck, would it be better to use ApplicationContext.ApplicationCache.RuntimeCache ?  (I'm not sure of the pros / cons)

BTW, you can find this in the latest prerelease:

NuGet Package: [![MyGet build](https://img.shields.io/myget/nupickers/vpre/nuPickers.svg)](https://www.myget.org/gallery/nupickers)
Umbraco Package (zip file): [![AppVeyor Artifacts](https://img.shields.io/badge/appveyor-umbraco-orange.svg)](https://ci.appveyor.com/project/JeavonLeopold/nupickers/build/artifacts)

**Comment by drpeck** [comment]
@Hendy I don't know in truth. At CodeGarden 16, Sebastian and Shannon [held a session ](http://video.twentythree.net/12732915/13898422/ac1574b716a695e5cdb9b87561cf2c77/video_medium/je-suis-core-video.mp4?source=podcast) where they suggested that using that would at least make life easier for avoidance of writing extra code (and extra bugs). Potentially there are other benefits, but I binned off my bespoke caching classes since. 

I'm sure what you've done is fine and reduces dependencies. I only asked in case you had a view on why `ApplicationContext.ApplicationCache.RuntimeCache` wasn't up to the task.

**Comment by Jeavon** [comment]
@drpeck `AplicationContext.ApplicationCache.RuntimeCache` is a nice easy to use and tested API for `System.Runtime.Caching` but essentially it's the same as what @Hendy has implemented directly with `System.Runtime.Caching`
