### ISSUE TITLE
Use key in datasource as value in pickers

### ISSUE THREAD

**Issue by bjarnef** [uComponents/nuPickers#151]
I have tried creating a language picker using DotNet datasource and a dropdown as picker: https://github.com/uComponents/nuPickers/wiki/Data-Source-DotNet

I used this example to get backoffice languages https://gist.github.com/ninjaonsafari/b2fe35271d6ddee4a38a07e6b6dfc4d1 but also created a datasource for specific cultures:

```
public class LanguagesDataSource : IDotNetDataSource
{
    IEnumerable<KeyValuePair<string, string>> IDotNetDataSource.GetEditorDataItems(int contextId)
    {
        // return a collection of key / labels for picker
        var list = Enumerable.Empty<KeyValuePair<string, string>>().ToList();

        var languages = new List<CultureInfo>()
        {
            CultureInfo.CreateSpecificCulture("da-DK"),
            CultureInfo.CreateSpecificCulture("nb-NO"),
            CultureInfo.CreateSpecificCulture("sv-SE")
        };

        foreach (var language in languages)
        {
            list.Add(new KeyValuePair<string, string>(language.Name, language.EnglishName));
        }

        return list;
    }
}
```

I would expect it to use the key as value in the dropdown, but no matter which value I use as key, it always return values like: 0, 1, 2, 3, 4, etc..

![image](https://cloud.githubusercontent.com/assets/2919859/19619765/91c7777c-986e-11e6-9a1b-0ff8b71f2bf7.png)

I would like to return culture codes instead like: da-DK, nb-NO, sv-SE, en-GB etc.

**Comment by bjarnef** [comment]
When changing to radiobutton it does use culture name as value:

![image](https://cloud.githubusercontent.com/assets/2919859/19619837/00d98bea-9870-11e6-8284-20f564c6a97a.png)

**Comment by bjarnef** [comment]
Checkboxlist also use the correct value:

![image](https://cloud.githubusercontent.com/assets/2919859/19619882/e82618d8-9870-11e6-8350-1ccae6a2e635.png)

**Comment by bjarnef** [comment]
It doesn't specify the key in DropDownPickerEditor https://github.com/uComponents/nuPickers/blob/master/source/nuPickers/Shared/DropDownPicker/DropDownPickerEditor.html

as it does in RadioButtonPickerEditor https://github.com/uComponents/nuPickers/blob/master/source/nuPickers/Shared/RadioButtonPicker/RadioButtonPickerEditor.html

It could do something like this in ng-options http://stackoverflow.com/a/21734643

**Comment by bjarnef** [comment]
Okay, it does seem to work now even it display 0, 1, 2 etc. the model use the key.
I think I might have chosen the other language datasource which use an id as key, when testing both.

**Comment by oliverEvry** [comment]
Hi!

How did you solve this, I´m having a similar error. Please see:
https://github.com/uComponents/nuPickers/issues/200
or
https://our.umbraco.com/packages/backoffice-extensions/nupickers/questionssuggestions//100435-nupickers-dotnet-dropdown-picker-only-render-keys-how-to-render-values

/Oliver

**Comment by bjarnef** [comment]
@oliverEvry I had the following .NET data sources. The first one add specific languages the second one add languages from backoffice.

```
public class LanguagesDataSource : IDotNetDataSource
{
    IEnumerable<KeyValuePair<string, string>> IDotNetDataSource.GetEditorDataItems(int contextId)
    {
        // return a collection of key / labels for picker
        var list = Enumerable.Empty<KeyValuePair<string, string>>().ToList();

        var languages = new List<CultureInfo>()
        {
            CultureInfo.CreateSpecificCulture("da"),
            CultureInfo.CreateSpecificCulture("no"),
            CultureInfo.CreateSpecificCulture("sv")
        };

        foreach (var language in languages)
        {
            // using culture name as key, e.g. "da", "no" and "sv"
            list.Add(new KeyValuePair<string, string>(language.Name, language.EnglishName));
        }

        return list;
    }
}

public class BackofficeLanguagesDataSource : IDotNetDataSource
{
    IEnumerable<KeyValuePair<string, string>> IDotNetDataSource.GetEditorDataItems(int contextId)
    {
        var list = Enumerable.Empty<KeyValuePair<string, string>>().ToList();
        var localizationService = ApplicationContext.Current.Services.LocalizationService;
        var languages = localizationService.GetAllLanguages();

        foreach (var language in languages)
        {
            // using id as key
            list.Add(new KeyValuePair<string, string>(language.Id.ToString(), language.CultureInfo.DisplayName));
        }

        return list;
    }
}
```

Try with the different editors: dropdownlist, checkboxlist, radiobuttonlist and get the value as string to see the raw value `GetPropertyValue<string>("nuPickerPropertyName")`.

**Comment by oliverEvry** [comment]
@bjarnef  Okey, but where you able to display the values and not the keys when using dropdownlist?

**Comment by bjarnef** [comment]
@oliverEvry yes, in this case it was used inside nested content.

![image](https://user-images.githubusercontent.com/2919859/71072907-b33e7700-217f-11ea-8a0b-8f0892fbf43f.png)

```
var nestedElements = Model.Content.GetPropertyValue<IEnumerable<IPublishedContent>>("myNestedProp");

    foreach (var element in nestedElements)
    {
        var lang = element.GetPropertyValue<Picker>("lang");
    
        @lang.SavedValue
    }
```

The `SavedValue` returned the key value from the dropdownlist, so e.g. `da-DK`.

**Comment by oliverEvry** [comment]
@bjarnef  But isn´t that because you have example `da-DK` as key to value `Danish (Denmark)` , thereby you are rendering the `key` and not the `value`?

**Comment by bjarnef** [comment]
@oliverEvry yes, the dropdown is storing the key in this case `da-DK`. I didn't use the actual value from the dropdown only to display the value in the dropdown.
