### ISSUE TITLE
Relation Labels incredibly slow - 4.5 minutes to populate

### ISSUE THREAD

**Issue by jeeby** [uComponents/nuPickers#153]
On an Umbraco 7.4.3 site i'm supporting, which has nuPickers installed (not sure which version - how can i  check this?), I have a Relation Labels control on a doc type.  It works, just really really slowly.

Currently it's taking about 4.5 minutes to render a list of about 90 relations.

Is this a known issue?  This worked better at one stage in the past, but not really sure what's slowed it down more recently.

Is there a way I can debug where the delay is (short of downloading the source code, hooking it up and stepping into the code myself)?

Any suggestions would be welcome, as currently it's looking like a bug in the control itself.

**Comment by Hendy** [comment]
Hi, are you doing anything complex with custom labels at all ? (getting relation data should be a single SQL query, so relatively fast)

**Comment by Hendy** [comment]
Hi @jeeby, closing this, but will re-open if we can identify an issue.
