### ISSUE TITLE
Console error when datasource returns empty result

### ISSUE THREAD

**Issue by bjarnef** [uComponents/nuPickers#157]
I am using nuPickers v1.5.3 and have a DotNet datasource to populate a dropdownlist with data from a json-file. However when it returns not results (empty result), there is a console error.

`TypeError: Cannot read property 'key' of undefined`

![image](https://cloud.githubusercontent.com/assets/2919859/22503172/cc5517b2-e870-11e6-810e-eb17bcd47816.png)

Using the dropdownlist in LeBlender property:

![image](https://cloud.githubusercontent.com/assets/2919859/22503192/e2529f1c-e870-11e6-9e45-ebbc393e145a.png)

It happens because, it access `key` of `$scope.dropDownPickerOptions[i]`, but `$scope.dropDownPickerOptions[i]` is undefined.

![image](https://cloud.githubusercontent.com/assets/2919859/22503274/486c0766-e871-11e6-9c65-bb521565f07d.png)

For example try with a DotNot datasource like this:

```
public class MyDotNetDataSource : IDotNetDataSource
{
    IEnumerable<KeyValuePair<string, string>> IDotNetDataSource.GetEditorDataItems(int contextId)
    {
        // return a collection of key / labels for picker
        var list = Enumerable.Empty<KeyValuePair<string, string>>().ToList();

        return list;
    }
}
```

**Comment by Hendy** [comment]
issue occurs when there is an existing saved value, and an empty collection is returned
