### ISSUE TITLE
Sorting of picked items in nuPickers.XmlPrefetchListPicker won't be saved.

### ISSUE THREAD

**Issue by enkelmedia** [uComponents/nuPickers#161]
I've noticed that the sort-order of items (when sorting is enabled) does not get saved when you use the "relation"-setting for the picker.

**Comment by Hendy** [comment]
Hi @enkelmedia is this with a "relations only" save format ?

**Comment by enkelmedia** [comment]
Thats right!

**Comment by Hendy** [comment]
Hi @enkelmedia Thanks for your pull request :) have taken a quick look and can see that you're now storing the sort order data in the relations XML fragment 👍

**Comment by enkelmedia** [comment]
@Hendy Yes, otherwise the updated sort order would not be updated since the earlier version ignored all relations that was already existing. I've tested it with the xml-picker but not all other ways of using it.
