### ISSUE TITLE
What is the best approach for member images?

### ISSUE THREAD

**Issue by akeilox** [uComponents/nuPickers#165]
I have used nuPickers.DotNetPrefetchListPicker with a simple App_Code/nuDataSource.cs

which fetches member images from a third party database;

select name, imageBase64 ... from 3rdpartyDBtable ..

and shows in the listview as image to select. User can select the member's picture (one or multiple) and save the selected id in data type (csv).

However this is far from ideal as each load of data-type it'll show all pictures of all members which takes a toll with all members' base64 images being loaded and displayed in page.

For such a simple scenario of using Member Image Selector, what approach would you suggest with nuPickers?

Would appreciate your input and thoughts greatly!

**Comment by Hendy** [comment]
Hi @akeilox if you have lots of members, would the DotNetTypeaheaadListPicker be of any use ? 
(there is also issue #37 to implement a PagedListPicker)

**Comment by akeilox** [comment]
Hi Hendy thanks for swift reply! The moment i submitted my question I was thinking how viable would it be to have "Load more.." at the bottom of 10 images at-a-time so the new data type with paging definitely sounds great. Is there any timeline on when that can be realized for the basic data type at the least?

I have tried doing a demo with typeAheadListPicker but that didnt turn out that well, and it was slow probably because I was trying to parse all images.

For a use case where user can see the recent joined member photos and select one or multiple from that makes the most sense. It becomes more intuitive than trying to recall a name or enter words rather than seeing on page the most recently joined ones.

I guess the pagedListPicker makes perfect sense in this use case, because user gets to see page 1 on load and browses page 2/3/4 easily without comprising speed and typing anything.

**Comment by Hendy** [comment]
Hi @akeilox there's a new DotNet PagedListPicker in the latest [bleeding-edge](https://ci.appveyor.com/project/JeavonLeopold/nupickers/build/artifacts) build: 
![image](https://cloud.githubusercontent.com/assets/77045/25529442/ed341518-2c19-11e7-949b-6d9bf3c0e737.png)
