### ISSUE TITLE
Custom label not working anymore

### ISSUE THREAD

**Issue by jbreuer** [uComponents/nuPickers#166]
I've upgraded from nuPickers 1.5.3 to 1.6.1 (running Umbraco 7.5.13) and now my custom label isn't working anymore. 

How it looked before:
![sidekick](https://cloud.githubusercontent.com/assets/5444597/25237429/f4b27530-25ea-11e7-8708-835085859e51.png)

How it looks now:
![sidekick2](https://cloud.githubusercontent.com/assets/5444597/25237438/fc6f5f9a-25ea-11e7-8151-026b6d0808fa.png)

The datatype still has the custom label selected and the macro also didn't change. When I debug the razor file it get's hit and everything seems normal. Here is the razor file:

```
@using Newtonsoft.Json
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@{
    var key = Model.MacroParameters["key"].ToString();
    dynamic sidekick = JsonConvert.DeserializeObject(Model.MacroParameters["label"].ToString(), new JsonSerializerSettings { TypeNameHandling = TypeNameHandling.Auto }); 
}
<style type="text/css">
    .sidekicks img {
        width: 56px;
        height: 56px;
        border-radius: 50%;
        overflow: hidden;
        border: 2px solid #27348B;
        margin-left: -4px;
        margin-top: 3px;
    }

     .data {
         background-color: #fff;    
         font-size: 10px;
         color: #000;
         width: 100%;
         -ms-opacity: 0.8;
         opacity: 0.8;
         padding: 5px;
         position: relative;
     }

    .data div {
        padding: 0;
        margin: 0;
        line-height: 15px;
        position: absolute;
        top: -80px;
        left: 17px;
    }
</style>
<div>
    <div class="sidekicks">
        <div>
            <img src="@sidekick.ImageUrl" />
            <div class="data">
                <div>
                    @sidekick.Name
                </div>
            </div>
        </div>
    </div>
</div>
```

So the razor file is executed, but somehow it's not rendered.

**Comment by Hendy** [comment]
Hi @jbreuer, 
The custom label code hasn't changed in this release, but the way data-sources are called has (they all now use a common method), but custom labels are working here on my test site. Can I ask which data-source you are using ?

**Comment by Hendy** [comment]
(we also need to have a field for custom css, rather than having to have it in the macro - I'll raise that as another issue)

**Comment by Hendy** [comment]
Hi @jbreuer I'm guessing the label it is currently rendering (the raw JSON) is the actual label value you're providing, before it should be processed by the custom label macro ?

**Comment by Hendy** [comment]
I can reproduce this in Umbraco 7.5.11 using the macro above with the following data source:

```
    public class JsonLabels_166Test : IDotNetDataSource
    {
        /// <summary>
        /// returns keys with labels containing json data (so it can be deserialized and consumed in a custom label)
        /// </summary>
        IEnumerable<KeyValuePair<string, string>> IDotNetDataSource.GetEditorDataItems(int contextId)
        {
            Dictionary<string, string> items = new Dictionary<string, string>();

            items.Add("key1", "{\"Key\": \"3304\", \"Name\": \"Monty\", \"ImageUrl\" : \"/media/unknown.jpg?anchor=center&model=crop&width=112&height=112\" }");
            items.Add("key2", "{\"Key\": \"3305\", \"Name\": \"Biggles\", \"ImageUrl\" : \"/media/unknown.jpg?anchor=center&model=crop&width=112&height=112\" }");
            items.Add("key3", "{\"Key\": \"4647\", \"Name\": \"Winston\", \"ImageUrl\" : \"/media/unknown.jpg?anchor=center&model=crop&width=112&height=112\" }");
            items.Add("key4", "{\"Key\": \"4648\", \"Name\": \"Praline\", \"ImageUrl\" : \"/media/unknown.jpg?anchor=center&model=crop&width=112&height=112\" }");

            return items;
        }
    }
```

**Comment by Hendy** [comment]
Hi @jbreuer, neat way of supplying data to the macro :) can I check that you are using a DotNet data source ? (although I'm not sure how that would have worked in v1.5.3)

**Comment by jbreuer** [comment]
Thanks for looking into this. Yes it's the DotNet data source. We're using the DotNetRadioButtonPicker. DIdn't have the issue in 1.5.3. Only in 1.6.1.

**Comment by Hendy** [comment]
@jbreuer looking at the 1.5.3 code, it had a .ToList() that I missed. Thanks.

**Comment by jbreuer** [comment]
Just tested 1.6.2. Now it's working again. Thanks!
