### ISSUE TITLE
remove public method from data-sources

### ISSUE THREAD

**Issue by Hendy** [uComponents/nuPickers#168]
Technically a Breaking Change ! but nothing should be using these methods.  (all public access to nuPickers should be via the Picker obj or the IDotNetDataSource interfaces)

v1.6.0 change IDataSource implementations to be explicit (internal interface)
vPrevious change public GetEditorDataItems(int contextId) method to become private

**Comment by sniffdk** [comment]
Hi Hendy
Just tried to update to nuPickers 1.7, but ran into a problem where our code uses the GetEditorDataItems mehod:

```
var datasource = new nuPickers.Shared.JsonDataSource.JsonDataSource
{
    Url = "~/App_Plugins/ColorTheme/bg-colors.json",
    JsonPath = "$..*",
    KeyJsonPath = "class",
    LabelJsonPath = "name"
};
BgColors.AddRange(datasource.GetEditorDataItems(0).Select(x => x.Key));
```

Any idea how to modify that code to get the same functionality?
