### ISSUE TITLE
Upgrade from 1.5.2 to 1.7.0

### ISSUE THREAD

**Issue by pauldambra** [uComponents/nuPickers#174]
Hey,

We have a json drop down picker. In our controller we use `content.GetPropertyValue<Picker>(somepropertyName);` to get a picker and then `SavedValue` to get the user's choice.

Running with 1.5.2 the `Object` that `SavedValue` returns is an int and at 1.7.0 it's a string.

The reason that's a problem for us is that we then cast the int to some enum value which explodes when it's a string :(

Are we reading the value in the wrong way?

**Comment by pauldambra** [comment]
In case it helps it is a nuPickers.JsonDropDownPicker and save format is CSV...

**Comment by Hendy** [comment]
Hi @pauldambra sorry for a such late reply, looking though the change history looks like the SavedValue is always set to be the object supplied to the PropertyValueConverter by Umbraco. 

Perhaps when a CSV has one numeric item picked, something somewhere is converting that to an int ? whilst multples having commas are returned as strings ?

The Picker object [(see wiki)](../wiki/Model) has some helper methods which mean you don't need to parse the raw SavedValue, for example there's a AsEnums<T> helper.
