### ISSUE TITLE
PrefetchListPickers not working because of <ng-includes ... />

### ISSUE THREAD

**Issue by bowserm** [uComponents/nuPickers#178]
I have an Umbraco 7.4.3 site I am working on that had nuPickers 1.5.3 on it. We were using an Enum PrefetchListPicker. After upgrading to nuPickers 1.7.0, I noticed that the `ListPickerSelectedPartial.html` section of my list picker wasn't showing up. The html for it wasn't even in the DOM. I did some digging and found out that the problem was because of the way that nuPicker was doing `<ng-include ... />`. When two `<ng-include ... />` tags follow each other, they need to be written as `<ng-include ...></ng-include>` or the 2nd will be completely and silently omitted.

**Comment by bowserm** [comment]
I just made a pull request. This was really helpful when trying to figure it out in case anyone is curious.
https://stackoverflow.com/questions/25217260/using-nginclude-multiple-times-in-angularjs

**Comment by Hendy** [comment]
Thanks again, have merged in the PR
