### ISSUE TITLE
how to set an xpath according to a checkbox property selected?

### ISSUE THREAD

**Issue by nandoDev** [uComponents/nuPickers#181]
Hi, I'm using the xml checkbox picker to get a list of nodes with an alias "category" wich are under a node with alias "categories". The issue is that the document type  "category" has a property of data type checkbox list wich has two options: news and ads. 

So what i'm trying to achieve is that the checkbox list generated by the xml checkbox picker only show the  "category" nodes with for example the value 'news' selected or the value "ads" selected.

The xpath set for any other simple property type like TextString is this: //categories//category[testProperty = 'test'] so how could i get the categories with one of the checkbox options selected.

Please any help

**Comment by Hendy** [comment]
Hi, sorry for a late reply, can't say for sure what the XPath expression would be without knowing how the source checkbox (testProperty) saves its values - there are some XPath examples on this [wiki page](../wiki/Data-Source-Xml).
