### ISSUE TITLE
Controller.js not loading via ClientDependency in Load Balanced Enviro

### ISSUE THREAD

**Issue by organicglenn** [uComponents/nuPickers#20]
In a load balanced environment, I am forcing site admin to one box, so it's not load balanced, per Umbraco doc, but the Controllers aren't loading when ClientDependency is running.
When admin-ing my Data Type that uses xmlTypeAheadPicker, the screen doesn't render correctly and Chrome Dev shows the error:
Error: Argument 'nuComponents.DataTypes.Shared.ListPicker.ListPickerEditorController' is not a function, got undefined
In Chrome Dev, I cannot find that namespace when I search the scripts.

When admin-ing content that uses this DataType, the typeahead does not work and Chrome Dev shows the error:
error: Argument 'nuComponents.DataTypes.Shared.RelationTypeMapping.RelationTypeMappingConfigController' is not a function, got undefined

If I publish a debug version to turn OFF script bunding via ClientDependency then everything works.  I can find the namespace in Chrome in unminified /Umbraco/App_Plugins/nuComponents/DataTypes/Shared/TypeAheadListPicker

FYI, the other custom DataTypes are in /App_Plugins, not /Umbraco/App_Plugins, could that make a difference?

**Comment by usb710** [comment]
@Hendy @organicglenn  i have read all yours conversation. i got same issue with my nuPicker XML dropdown. as you fixed your issue  by adding some entries to the local hosts files on the web servers to prevent the CDF request from leaving the web server and that solved that problem.  Could you please tell me which entries you added and how to add these entries to local host files on web servers to prevent the CDF request from leaving the web server.. Please advise me and secondly if you could email me that dll file which stop Error 404 that will be very very appriciated.

**Comment by DanDiplo** [comment]
@usb710 I had same issue and eventually solved it by a combination of these actions (for a 7.2.1):

I updated NuPickers and Client Dependency in NuGet to latest versions

I empted the clientdependency cache in /App_Data/Temp/

I then updated the clientdependency.config file in /config/ with a domain name ( bundleDomains="YOURDOMAINHERE") *and* incremented the version number, as outlined in this thread: https://our.umbraco.org/forum/umbraco-7/using-umbraco-7/61145-Packages-only-work-in-debug-mode

Restarted the app pool (or touch web.config)

**Comment by usb710** [comment]
@DanDiplo  thanks you so much for your quick reply :) all working now Thank you so much again! :)
