### ISSUE TITLE
Relative url with ~/ not working as expected.

### ISSUE THREAD

**Issue by Thom3189** [uComponents/nuPickers#50]
Would it be possible to have the relative url use the current request's domain as the root of the url instead of using mappath to determine the actual location on disk of the requested path. This way we can use our own web api with the Json data picker for example.

**Comment by FIR55TORM** [comment]
I'm also having this issue. I can use the api via a full url but I don't particularly want to change the url between dev and live.

**Comment by Hendy** [comment]
Hi, can you describe how to reproduce this ? (relative urls with json pickers are working on a site here)

**Comment by FIR55TORM** [comment]
Ill have a look properly once I'm at my dev machine but I ran a new instance of umbraco 7.2.1 via nuget, installed nuPickers and made a quick umbraco api controller returning a simple string array. My Url looks like this: "~/Umbraco/Api/MyControllerName/MethodName" when not working. Ill try get more info soon.

**Comment by Hendy** [comment]
Hi, this should now be fixed: https://github.com/uComponents/nuPickers/commit/94cadcd33640c37faac41dc9170eff1813db5528

**Comment by FIR55TORM** [comment]
Fantastic!
