### ISSUE TITLE
Dependency Handler Error

### ISSUE THREAD

**Issue by kennyburns1967** [uComponents/nuPickers#61]
Hello,

I have an issue where nuPickers is working locally, but on the production environment, all of a sudden I am experiencing an error similar to this:

nuPickers.Shared.CheckBoxPicker.CheckBoxPickerEditorController' is not a function, got undefined    at Error (native)
DependencyHandler.axd?s=L3VtYnJhY…MuYmxvY2t0eXBlcy5jb250cm9sbGVyLm1pbi5qczs&t=Javascript&cdv=545262247:7:622
Any ideas what this might be? I tried deleting the client dependency folder but no joy.

Edit: when trying to set up a data type using the nupickers, I am getting an error whereby I cannot select the assembly. The error reads: 

"An error has occurred.","ExceptionMessage":"The 'ObjectContent`1' type failed to serialize the response body for content type 'application/json; charset=utf-8'.","ExceptionType":"System.InvalidOperationException","StackTrace":null,"InnerException":{"Message":"An error has occurred.","ExceptionMessage":"Could not load file or assembly '311296 bytes loaded from uComponents.nuPickers, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format."

Thanks in advance,

Kenny

**Comment by dawoe** [comment]
I'm having the same issue after upgrading the client dependency framework as advised in this post : http://umbraco.com/follow-us/blog-archive/2015/2/5/security-alert-update-clientdependency-immediately

Solutions for other comments don't work for me.

**Comment by dawoe** [comment]
I found a work around for this one. You need to set the domain of your website in the clientdependency framework config. Remove your clientdependency files in you app_data folder and restart your website.

<compositeFiles defaultProvider="defaultFileProcessingProvider" compositeFileHandlerPath="~/DependencyHandler.axd">
    <fileProcessingProviders>
      <add name="CompositeFileProcessor" 
		type="ClientDependency.Core.CompositeFiles.Providers.CompositeFileProcessingProvider, ClientDependency.Core" 
		enableCssMinify="true" 
		enableJsMinify="true" 
		persistFiles="true" 
		compositeFilePath="~/App_Data/TEMP/ClientDependency" 
		bundleDomains="YOURDOMAINHERE" urlType="Base64QueryStrings" pathUrlFormat="{dependencyId}/{version}/{type}" />
    </fileProcessingProviders>

    
    <fileMapProviders>
      <add name="XmlFileMap" type="ClientDependency.Core.CompositeFiles.Providers.XmlFileMapper, ClientDependency.Core" mapPath="~/App_Data/TEMP/ClientDependency" />
    </fileMapProviders>

</compositeFiles>

**Comment by nevenanikolic** [comment]
Hi everyone,

I'm having same issue with the Umbraco 7.1.8 and I just cannot get it to work.

I have tried everything, and by that I mean literary everything :)

Please, please - any ideas? :)

P.S. I just need to mention that I have worked on numerous Umbraco 7.1.8 projects and same issue appears on every single project.

Thanks, Nevena

**Comment by Jeavon** [comment]
@nevenanikolic are you using the latest release of nuPickers?

**Comment by nevenanikolic** [comment]
Hi @Jeavon, 

Thanks for replying. Apologise, but I have actually realised that I have commented on the wrong issue. 
http://issues.umbraco.org/issue/U4-6380 - is the why I'm desperate this Friday evening. 

I won't be replying on this issue anymore as whatever I have to say is not related to this one. 
However, do you have any possible ideas of what might be causing it and how to fix it? 

If you do, plese contact me (nevena.nikolic.ns@gmail.com) and if not - I wish you wonderful evening :)

Thanks and once again - apologise. 

Nevena

**Comment by Jeavon** [comment]
Seems you need to upgrade to v7.2.6 to fix it
