### ISSUE TITLE
Translation/localization of labels & descriptions

### ISSUE THREAD

**Issue by greystate** [uComponents/nuPickers#67]
Just wondering if anyone has done some work towards being able to translate the labels and descriptions/hints for these awesome pickers? What's required? Is there a preferred way to provide translations for custom property editors in V7 already?

/cc @Hendy, @Jeavon

**Comment by Hendy** [comment]
Hi @greystate TBH, not thought about how to translate the Label / Description - perhaps this could be done outside the scope of nuPickers, so it could be applied to all datatypes  ?

(of course the selectable items themselves could be translated via the Custom Label feature)

**Comment by greystate** [comment]
Thanks @Hendy - agree on keeping it outside of the nuPickers project; pretty sure there must be a "system" in place already for the built-in property editors, though. Will probably not be able to keep away from digging into it :-)

**Comment by Hendy** [comment]
Hi @greystate did you find a way ?

**Comment by greystate** [comment]
Hi @Hendy - sorry, no. Never got 'round to it; always seem to be something more important to tend to :cold_sweat:

**Comment by Hendy** [comment]
Closing, as this feature would probably best be handled outside of nuPickers.
