### ISSUE TITLE
Issue with loading DLL

### ISSUE THREAD

**Issue by revolution42** [uComponents/nuPickers#69]
I have been having an issue with loading the enum types it doesn't seem to work.

I tracked it back to loading a file "LinqToTwitter.AspNet.dll" from the Nuget package "https://www.nuget.org/packages/linqtotwitter".

Maybe need to switch to loadable types to be something suggested in http://stackoverflow.com/questions/11915389/assembly-gettypes-throwing-an-exception

**Comment by Hendy** [comment]
Hi @revolution42, do you know if that fix resolved this issue ?

**Comment by revolution42** [comment]
What I said did fix the issue, but I haven't updated to the latest so havent seen if your fix, fixes the issue.

**Comment by Hendy** [comment]
Thanks, I'll leave this open for the time being then

**Comment by revolution42** [comment]
The latest update fixes the issue. Thank you

**Comment by Hendy** [comment]
:+1:
