### ISSUE TITLE
ClientDependency change - time rethink embedded resources?

### ISSUE THREAD

**Issue by leekelleher** [uComponents/nuPickers#71]
@Hendy @Jeavon Due to a recent change in ClientDependency - it appears that requests to local resources that aren't physically on disk (e.g. embedded resources) need to have their domain white-listed.

See the commit here: Shazwazza/ClientDependency@6a9e22dffb0aab73cfe84b31d80b1fbedb43b7e0

This issue has been explained in detail here: #61

Is it time to rethink the embedded resources approach?

**Comment by leekelleher** [comment]
For reference, I've asked the question on the ClientDependency repo: [#50](https://github.com/Shazwazza/ClientDependency/issues/50)

**Comment by greystate** [comment]
:+1:

**Comment by Hendy** [comment]
HI @leekelleher I'm wondering about this again too - the majority of the issues raised on Our have been related to this. Perhaps the best of both world is needed, where the assets are still distributed within the dll, but on start-up the resources are extracted onto the file system ? // @Jeavon

**Comment by leekelleher** [comment]
I'm wondering how upgrades would work? Would we need to nuke the assets (CSS/JS) on disk, then extract the latest embedded ones?

Then there's the edge-cases, where developers have tinkered with the assets for their own customisations. Would they be overwritten?

**Comment by Hendy** [comment]
Could hash check any existing files, and if different, back them up into a folder ? (or take the simple approach and just mention the possibility of overwriting custom files in the release log since it's likely to be an edge case).

**Comment by greystate** [comment]
I'd be cool with a note about overwrites - if I've changed the files, I know my changes probably won't be upgradeable anyway...

**Comment by Jeavon** [comment]
IMO, it shouldn't be default behaviour to extract the resources, but I think we could check for a app setting key and if present extract the resources. Once /App_Plugins/nuPickers exists then it wouldn't extract again, so for upgrades it would be necessary to delete the folder and let it extract again. (it would also be necessary to add the .nu mime types to web.config if the key was present)
This would hopefully enable no VS developers to be able to contribute to the project.
I think think this gives us the best of all options.....?

**Comment by leekelleher** [comment]
Closing this issue. All discussed at the time.
