### ISSUE TITLE
Start node option

### ISSUE THREAD

**Issue by jbreuer** [uComponents/nuPickers#75]
It would be nice if some property editors would have a start node option like the default media picker and Multinode Treepicker. 

For example the nuPickers: Xml CheckBox Picker. Now you need an XPath to match all nodes which should be displayed. But a start node which should display just all child nodes in a CheckBox list would be handy. You could still have an XPath to filter out some child nodes which are of the wrong document type.

**Comment by Hendy** [comment]
What would happen when moving environments and the Ids were different ? (not an issue when using XPath etc...)

**Comment by jbreuer** [comment]
Than you would need to change the id, but that also goes for the default media picker start node and MNTP start node.

**Comment by Hendy** [comment]
@jbreuer this could still be done with XPath //*[@id=123]/child::*[@isDoc]
