### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by JimBobSquarePants** [uComponents/nuPickers#82]
Nobody likes doing it but it's important...

I'm playing about with nuPickers for the first time and it's very difficult to see exactly what everything does. I found myself guessing which property editor to choose.

I'm in the very lucky position of being able to chase everyone down on Skype but other developers are not so lucky.

Some parts of the docs are very concise.

https://github.com/uComponents/nuPickers/wiki/Property-Value-Converter

Others not so much.

https://github.com/uComponents/nuPickers/wiki/Data-Source-Json

How about a bit of a documentation drive? I find it helps me to understand my code better and helps reduce bugs as well as promoting contribution.

**Comment by Hendy** [comment]
I quite like documenting! but it takes time... got any useful tips you could add ?

Started a [![Join the chat at https://gitter.im/uComponents/nuPickers](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/uComponents/nuPickers?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

**Comment by JimBobSquarePants** [comment]
Loony! :stuck_out_tongue_winking_eye: 

I'll have a read through and see if there is any snippets of useful knowledge I could add.

**Comment by Hendy** [comment]
:+1:
