### ISSUE TITLE
Relative urls ~/ not working for XML data source

### ISSUE THREAD

**Issue by greystate** [uComponents/nuPickers#88]
I tried to create an XML DataSource CheckBox Picker and set the **Xml Data** to *Url*, and the **Url** to *~/Config/SiteSettings.config* which doesn't work. To be honest, I'm not really sure what '~/' means in the URL - the description says *"use the prefix ~/ to indicate a relative url"* - relative to what? I was guessing the site's root, but I may be wrong.

I'm also worried that maybe there's a security issue with access to the Config folder?

FWIW, I'm able to load the same config file from XSLT using `document('../Config/SiteSettings.config')` i.e., using a relative URL from the XSLT file.

If I put the file somewhere else and point to it with an absolute URL (e.g. as `'/assets/SiteSettings.xml'`) the picker works as expected. Would just be nice to keep the file in the Config folder, since it's really configuration for the site.

/Chriztian

**Comment by Hendy** [comment]
Hi @greystate you're correct, the **~/** should mean relative to the current site root (I'll spend some time on documentation soon, oh and thanks for updating the wiki :+1:) 

Out of interest does **~/App_Data/SiteSettings.config** work correctly ? (I know this was a fixed for JSON in #68) perhaps the XML data-source needs a similar fix ?

**Comment by greystate** [comment]
Just tried using the App_Data folder - doesn't seem to work.

**Comment by Hendy** [comment]
Cool, I'll fix this ASAP
