### ISSUE TITLE
Saving as XML stores custom label - bug or feature?

### ISSUE THREAD

**Issue by greystate** [uComponents/nuPickers#89]
I can't really decide if I think this is a bug or a feature - but the XML returned for a picked item usually looks like this:

```xml
<propertyAlias>
  <Picker>
    <Picked Key="1234"><![CDATA[Gold Standard]]></Picked>
  </Picker>
</propertyAlias>
```

When using the [Custom Labels][1] feature (awesome, by the way!) I get something akin to this, back in the XML:

```xml
<propertyAlias>
  <Picker>
    <Picked Key="1234"><![CDATA[<span style="color:#d3c191;">Gold Standard</span>]]></Picked>
  </Picker>
</propertyAlias>
```

I was under the impression that the custom label feature was purely for customizing the display in the backoffice... but as I said, I'm still undecided whether I think of this as a bug or a feature :-)

Is this behavior the same across all save methods (JSON, CSV etc...)?

[1]: https://github.com/uComponents/nuPickers/wiki/Custom-Labels

**Comment by Hendy** [comment]
Hi @greystate, It should be the same for JSON but not CSV. Both JSON and XML store the key and the label and this data is used to populate any selected items for the Typeahead pickers (as the source list may not contain the picked items, and it'll need to render them as per the Custom Label transform) - perhaps this should change as it's related to PR #84 ?

**Comment by Hendy** [comment]
I'm thinking feature - it's adding information, which can be ignored. It's the payload penalty for custom labels !

**Comment by greystate** [comment]
Having used it for a couple of days now, and getting the hang of it, I totally agree :)

**Comment by Hendy** [comment]
phew :)
