### ISSUE TITLE
LucenePrefetchListPicker only partially rendering

### ISSUE THREAD

**Issue by organicglenn** [uComponents/nuPickers#92]
I have a few datatypes using the LucenePrefetchListPicker.  Today, they began only partially rendering, only showing as a textbox and a plain text bulleted list of options.  No style or red/green buttons on them.

In the Log looks to be a relevant entry: 
2015-04-06 10:07:50,072 [7] WARN Umbraco.Core.PropertyEditors.LegacyPropertyEditorIdToAliasConverter - [Thread 248] A legacy GUID id was generated for property editor nuPickers.LucenePrefetchListPicker. This occurs when the legacy APIs are used and done to attempt to maintain backwards compatibility. Consider upgrading all code to use the new Services APIs instead to avoid any potential issues.

Filtering still works, so it seems the Angular controller is there, and I see a bunch of nuPicker controllers loaded via DependencyHandler.axd. Maybe the CSS is missing, but aren't the resources all in the dll installed(via NuGet)?  I can't seem to find CSS in the Chrome Dev Tools.

Thanks,
Thoughts?

**Comment by Hendy** [comment]
Hi @organicglenn, yes all the resources are within the dll - are you able to identify the change that caused this issue to appear ?

**Comment by organicglenn** [comment]
Ahh, the typical detective work revealed the 'nuPicker' relevant update to this post:
http://umbraco.com/follow-us/blog-archive/2015/2/5/security-alert-update-clientdependency-immediately
Unfortunately, setting bundledDomains in the .config file didn't work for me and I had to do a nuPicker and ClientDependency dll hot fix.  Problem solved.
Thanks for the response Hendy!

**Comment by Jeavon** [comment]
@organicglenn if you have the latest NuGet release versions of ClientDependency and nuPickers it should work?

**Comment by organicglenn** [comment]
Yes, that's what I did, sorry I didn't make that clear.  Thanks Jeavon.

**Comment by Jeavon** [comment]
Phew, great!
