### ISSUE TITLE
When enabling 'filter' in XML Prefetch List the API is called twice

### ISSUE THREAD

**Issue by vnbaaij** [uComponents/nuPickers#94]
As the topic says: If you enable the filter property on a xml prefetch list GetEditorDataItems is called twice with the exact same parameters. First in ListPickerEditorController.js (line 139) and then again in PrefetchListPickerEditorController.js (line 13).

**Comment by Hendy** [comment]
Hi @vnbaaij don't suppose you want to have a go at this ? (The ListPickerEditorController could listen for data sent by the PrefetchListPickerEditorController)

**Comment by vnbaaij** [comment]
@Hendy I will give it a shot, but js/angular are not my best skills. Can't promise a working result...

I'll work on this n my spare time so don't have a solid planning. Keep you posted

**Comment by vnbaaij** [comment]
Oops. Wrong button :( #h5is

**Comment by Hendy** [comment]
:+1:  no worries @vnbaaij it would definitely be an improvement, but don't see it as essential as it currently works

**Comment by Hendy** [comment]
This has been fixed (in branch 'feature/paged-list-picker') as a consequence of moving the responsibility of getting the selectable options & selected options into the specific list picker type, and out of the 'base' ListPickerEditorController
