### ISSUE TITLE
Related Items

### ISSUE THREAD

**Issue by purna** [uComponents/nuPickers#96]
I'm using the nuPickers: Xml Prefetch list  (Data Type) as part of an update from umbraco 6 > 7 (trying to dump uComponents : Relation Links)

However the parentId and childId have swapped position when saving/publishing in the database table - umbracoRelation

As you can see from the table below : 

**Before**

| id | parentId  | childId | relType | DateTime | comment |
| --- | --- | --- | --- | --- | --- |
| #### | 10575 | 4365 | 5 | 18:05.0 | ["PropertyTypeId":718] |

**After**

| id | parentId  | childId | relType | DateTime | comment |
| --- | --- | --- | --- | --- | --- |
| #### | 4365 | 10575 | 5 | 11:09.8 | RelationMapping PropertyAlias="relateAgeRange" PropertyTypeId="718" ... |

Is there a way to set the direction saved/viewed? can this be added?

**Comment by Hendy** [comment]
Hi @purna I swapped the parent child, as thought it more likely to lookup on the parent Id (ie from the picked to the item that picked it), but TBH, didn't really consider an upgrade path :( I wonder if a sql script to swap the parent and child, and then force a complete re-publish of everything to force the comment field to update would do the trick ?

**Comment by purna** [comment]
I've a feeling most of the changes might need this. Yes I was going to change it via an sql script, but wanted to check the comment field was subservient to the id's. BTW - I'd like an SQl script to convert DAMP to the new Picker XML

Eg 
`<DAMP fullMedia=""><mediaItem><Image id="10635"  ...`
to 
`<Picker><Picked Key="10635">...`

What do you think. Is that the best route to take?

After that it only leaves the 'uComponents : Render Marco' to figure out!! (Any time frame on supporting that one?)

**Comment by Hendy** [comment]
Hi @purna, just a thought, but instead of a custom SQL script, there's an option on the previous mapping data type (uComponents: Multi Picker Relations or Umbraco: Picker Relations - https://ucomponents.codeplex.com/wikipage?title=MultiPickerRelations) to swap the order: "reverse indexing", however you'll still need to force the a full re-save to update the comment fields.
